# Generated by Django 2.0 on 2017-12-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20171221_1143'),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_mysql',
            name='data_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.data_centers', verbose_name='数据中心'),
        ),
        migrations.AlterField(
            model_name='db_mysql',
            name='db_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.db_users', verbose_name='数据库登陆用户'),
        ),
        migrations.AlterField(
            model_name='db_mysql',
            name='hostname',
            field=models.CharField(max_length=64, unique=True, verbose_name='数据库名字'),
        ),
        migrations.AlterField(
            model_name='db_mysql',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='db_mysql',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='数据库型号'),
        ),
        migrations.AlterField(
            model_name='db_mysql',
            name='port',
            field=models.IntegerField(blank=True, default='3306', null=True, verbose_name='端口'),
        ),
    ]
