# Generated by Django 2.0 on 2018-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebase',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d57856', verbose_name='代码包'),
        ),
    ]
