# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='外网IP')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('data_center', models.CharField(blank=True, max_length=64, verbose_name='数据中心')),
                ('cabinet', models.CharField(blank=True, max_length=64, null=True, verbose_name='机柜')),
                ('position', models.CharField(blank=True, max_length=64, null=True, verbose_name='位置')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘')),
                ('port', models.CharField(blank=True, max_length=256, null=True, verbose_name='上联端口')),
                ('use', models.BooleanField(verbose_name='是否在用')),
                ('ship_time', models.DateField(blank=True, verbose_name='出厂时间')),
                ('end_time', models.DateField(blank=True, verbose_name='到保时间')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='product_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line_list', models.CharField(max_length=128, null=True, verbose_name='产品线')),
            ],
            options={
                'verbose_name': '产品线',
                'verbose_name_plural': '产品线',
                'db_table': ' product_line',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.product_line', verbose_name='产品线'),
        ),
    ]
