# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='network_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='外网IP'),
        ),
    ]
