# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/%Y%m%d'),
        ),
    ]
