# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='%Y%m%d'),
        ),
    ]
