# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170831_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='到保时间'),
        ),
    ]
