# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('asset', '0002_auto_20170908_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_users',
            name='product_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='产品线'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='network_ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='外网IP'),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='product_line',
        ),
        migrations.AddField(
            model_name='asset',
            name='product_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='产品线'),
        ),
        migrations.DeleteModel(
            name='product_lines',
        ),
    ]
