# Generated by Django 2.0 on 2017-12-30 16:12

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20171229_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hostnam2',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d42961', verbose_name='文件'),
        ),
    ]
