# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20170831_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='end_time',
            field=models.DateField(default='1970-01-01', verbose_name='到保时间'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ship_time',
            field=models.DateField(default='1970-01-01', verbose_name='出厂时间'),
        ),
    ]
