# Generated by Django 2.0 on 2017-12-30 16:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20171230_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='hostnam2',
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d62526', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=256, null=True, verbose_name='登陆密码')),
        ),
    ]
