# Generated by Django 2.0 on 2017-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20171230_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d33330', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='登陆密码'),
        ),
    ]
