# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20170904_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_users',
            name='ps',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='port',
            field=models.IntegerField(blank=True, default='22', null=True, verbose_name='ssh端口'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='system',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本'),
        ),
    ]
