# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20170904_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_users',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='名称'),
        ),
    ]
