# Generated by Django 2.0 on 2017-12-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20171230_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d18302', verbose_name='文件'),
        ),
    ]
