# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20170904_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_users',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='system_users',
            name='utime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='登陆密码'),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='username',
            field=models.CharField(max_length=64, null=True, verbose_name='登陆用户'),
        ),
    ]
