# Generated by Django 2.0 on 2017-12-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20171230_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': {('read_asset', '只读资产管理'), ('task_asset', '执行资产')}, 'verbose_name': '资产管理', 'verbose_name_plural': '资产管理'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d52387', verbose_name='文件'),
        ),
    ]
