# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20170904_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hostnaem',
            field=models.CharField(max_length=64, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='登陆用户'),
        ),
    ]
