# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20170904_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='hostnaem',
            new_name='hostname',
        ),
    ]
