# Generated by Django 2.0 on 2017-12-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20171230_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d94527', verbose_name='文件'),
        ),
    ]
