# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20170920_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='inner_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d77878'),
        ),
    ]
