# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 15:55
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20170905_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_use', models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU使用率')),
                ('mem_use', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存使用率')),
                ('in_use', models.CharField(blank=True, max_length=32, null=True, verbose_name='进流量')),
                ('out_use', models.CharField(blank=True, max_length=32, null=True, verbose_name='出流量')),
                ('cdate', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('udate', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '监控状态',
                'verbose_name_plural': '监控状态',
                'db_table': 'performance',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='主机名'),
        ),
        migrations.AddField(
            model_name='performance',
            name='asset_server',
            field=models.ForeignKey(on_delete=builtins.callable, to='asset.asset'),
        ),
    ]
