# Generated by Django 2.0 on 2017-12-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20171230_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d92866', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='名称'),
        ),
    ]
