# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20170905_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='cpu_use',
            field=models.CharField(max_length=32, verbose_name='CPU使用率'),
        ),
    ]
