# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20170905_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='asset_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
    ]
