# Generated by Django 2.0 on 2017-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20171230_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d56481', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(default='100000', primary_key=True, serialize=False),
        ),
    ]
