# Generated by Django 2.0 on 2017-12-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20171230_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d60242', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(default='10000', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='system_users',
            name='id',
            field=models.AutoField(default='20000', primary_key=True, serialize=False),
        ),
    ]
