# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 17:00
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20170905_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='asset_server',
            field=models.ForeignKey(on_delete=builtins.callable, to='asset.asset'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='cpu_use',
            field=models.CharField(max_length=32, verbose_name='CPU使用率'),
        ),
    ]
