# Generated by Django 2.0 on 2018-01-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20171230_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='%Y%m%d93664', verbose_name='文件'),
        ),
    ]
