# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_auto_20170905_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='server',
        ),
        migrations.AlterField(
            model_name='performance',
            name='cpu_use',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CPU使用率'),
        ),
    ]
