# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 17:11
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_auto_20170905_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='server',
            field=models.ForeignKey(default=1, on_delete=builtins.callable, to='asset.asset'),
            preserve_default=False,
        ),
    ]
