# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_performance_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset'),
        ),
    ]
