# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_auto_20170905_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-cdate'], 'verbose_name': '监控状态', 'verbose_name_plural': '监控状态'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='data_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.data_centers', verbose_name='数据中心'),
        ),
    ]
