# Generated by Django 2.0 on 2017-12-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsscript',
            options={'permissions': {('read_toolsscript', '只读资产管理')}, 'verbose_name': '工具', 'verbose_name_plural': '工具'},
        ),
    ]
