# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='工具名称')),
                ('tool_script', models.TextField(verbose_name='脚本')),
                ('tool_run_type', models.IntegerField(choices=[(0, 'shell'), (1, 'python'), (2, 'yml')], default=0, verbose_name='脚本类型')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='工具说明')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'db_table': 'tools_script',
            },
        ),
    ]
