# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_toolsscript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsscript',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='工具名称'),
        ),
    ]
