# Generated by Django 2.0 on 2017-12-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20171230_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsscript',
            options={'verbose_name': '工具', 'verbose_name_plural': '工具'},
        ),
    ]
