# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='status',
            field=models.CharField(blank=True, choices=[('测试机', '测试机'), ('云主机', '云主机')], default='admin', max_length=12, null=True, verbose_name='用户权限'),
        ),
    ]
