# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_auto_20170908_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='users',
        ),
        migrations.DeleteModel(
            name='name',
        ),
    ]
